---
title: "{{stringr::str_replace_all(folder_name, stringr::fixed('-'), stringr::fixed(' '))}}"
date: "`r format(Sys.Date(), format='%B %d, %Y')`"
format:
  docx:
    reference-doc: templates/doc_template.docx
  html:
    toc: true
    toc-float: true
    toc-depth: 2
    toc-location: left
embed-resources: true
execute:
  echo: false
  warning: false
  message: false
bibliography: templates/references.bib
csl: templates/european-urology.csl
---

<!-- YAML options for both HTML and Word documents are given here. Delete output type not being used. -->

<!-- To cite a reference within the document, the ref must be included in the `templates/references.bib` file. Use square brackets and @ with the shorthand term. Ex: The generalized additive model models the relationship between the mean of the response variable and sum of smooth functions of the explanatory variables [@hastie1986gam]. -->

```{r setup}
# set chunk defaults, code chunks are NOT printed in output for report
#| include: false
set.seed({{format(Sys.Date(), format = "%Y%m%d")}})
```

```{r}
#| label: import
#| include: false
library(biostatR); library(tidyverse)
# setting MSK ggplot theme, gtsummary theme, and color palette
theme_set(mskRvis::theme_biostat()); theme_gtsummary_msk("hot"); mskRvis::set_msk_palette()

# Import analysis result objects here
load(here_data("results.Rdata"))
```

```{r}
#| label: inline_text
#| include: false

# define complex inline-reporting objects here
```

# Methods

Describe cohort and analytic methods here.

All analyses were conducted using `r cite_r(pkgs = c("gtsummary", "tidyverse"), add_citation = TRUE)`.

# Results

Describe analytic results here.

# Tables & Figures


# References
