---
title: "Report"
author: "Karissa Whiting"
date: "`r format(Sys.time(), '%B %d, %Y')`"
knit: (function(inputFile, encoding) {
    rmarkdown::render(inputFile, 
    output_dir = here::here("outputs"))
     })
output:
  html_document:
    theme: sandstone
    toc: yes
    toc_float: yes
    number_sections: true
fontsize: 12pt
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
# set chunk defaults, code chunks are NOT printed in output for report
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)

set.seed({{format(Sys.Date(), format = "%Y%m%d")}})
```

```{r import, include=FALSE}
library(biostatR)
library(tidyverse)

# setting MSK ggplot theme and color palette
theme_set(mskRvis::theme_biostat())
mskRvis::set_msk_palette()

# Import analysis result objects here
results <- load(here_data("results.Rdata"))
```

```{r inline_text, include=FALSE, echo=FALSE}
# define complex inline-reporting objects here
```

# Methods

Describe cohort and analytic methods here.

All analyses were conducted using R `r getRversion()`.

# Results

Describe analytic results here.

# Tables & Figures

# References
