---
title: "Report"
date: "Last Updated: `r format(Sys.Date(), format = '%B %d, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
  word_document:
    reference_docx: "`r here::here('templates/doc_template.docx')`"
bibliography: "`r here::here('templates/references.bib')`"
---

<!-- YAML options for both HTML and Word documents are given here. Delete output type not being used. -->
<!-- To cite a reference within the document, the ref must be included in the `templates/references.bib` file. Use square brackets and @ with the shorthand term. Ex: The generalized additive model models the relationship between the mean of the response variable and sum of smooth functions of the explanatory variables [@hastie1986gam]. -->

```{r setup, include=FALSE}
# set chunk defaults
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
set.seed({{format(Sys.Date(), format = "%Y%m%d")}})
```

```{r import, include=FALSE}
library(biostatR); library(tidyverse)

# setting MSK ggplot theme, color palette, and gtsummary theme
theme_set(mskRvis::theme_biostat()); mskRvis::set_msk_palette()
{{(ifelse(tolower(Sys.info()[["user"]]) %in% eval(as.list(bstfun::theme_gtsummary_msk)$name), glue::glue("theme_gtsummary_msk('{tolower(Sys.info()[['user']])}')"), "theme_gtsummary_compact()"))}}

# Import analysis result objects here
load(here_data("results.Rdata"))
```

```{r inline_text, include=FALSE, echo=FALSE}
# define complex inline-reporting objects here
```

# Methods

Describe cohort and analytic methods here.

All analyses were conducted using `r cite_r(pkgs = c("tidyverse", "gtsummary"), add_citation = TRUE)`.

# Results

Describe analytic results here.

# Tables & Figures

# References
